pdf: project2.md
	pandoc -S --template=template.tex -o cepko-p2-d1.pdf --filter pandoc-citeproc project2.md; evince cepko-p2-d1.pdf
doc: project2.md
	pandoc -S -o cepko-p2-d1.docx --filter pandoc-citeproc project2.md; libreoffice cepko-p2-d1.docx
